monitoring:
  metrics_interval: 1.0  # seconds between metric collections
  max_history_days: 30   # days to keep historical data
  alert_thresholds:
    cpu_percent: 80      # CPU usage alert threshold
    memory_percent: 85   # Memory usage alert threshold
    response_time_ms: 5000  # Response time alert threshold
    gpu_memory_percent: 90  # GPU memory alert threshold
    error_rate_percent: 5   # Error rate alert threshold

dashboard:
  host: "0.0.0.0"
  port: 8080
  update_interval: 1000  # milliseconds between dashboard updates
  max_chart_points: 1000 # maximum points to show in charts

api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  log_level: "info"

database:
  sqlite_path: "data/monitoring.db"
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0

logging:
  level: "INFO"
  format: "json"
  file: "logs/monitoring.log"
  max_size_mb: 100
  backup_count: 5

alerts:
  enabled: true
  webhook_url: null  # Optional webhook for alerts
  email:
    enabled: false
    smtp_server: null
    smtp_port: 587
    username: null
    password: null
    to_addresses: [] 